#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';
define('__ROOT__', dirname(__FILE__).'/..');

// Include the main Propel script
require_once __ROOT__.'/app/vendor/propel/propel1/runtime/lib/Propel.php';

// Initialize Propel with the runtime configuration
Propel::init(__ROOT__."/app/config/code2be-conf.php");

use Symfony\Component\Console\Application;
use Code2be\Command\FixturesCommand;

$console = new Application();
$console->add(new FixturesCommand);
$console->run();
